name: Puppeteer Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install
      
    - name: Run Puppeteer tests
      run: npm test ./testing/__tests__/puppeteer.test.js